import { AlertTriangle, CheckCircle2, Clock3 } from 'lucide-react'
import type { ClinicalPatient, RiskLevel } from './types'

export const riskTone: Record<RiskLevel, string> = { Low:'bg-emerald-50 text-emerald-700', Medium:'bg-yellow-50 text-yellow-700', High:'bg-orange-50 text-orange-700', Critical:'bg-red-50 text-red-700' }

export function RiskBadge({risk}:{risk:RiskLevel}) { return <span className={`rounded-full px-2 py-1 text-xs font-semibold ${riskTone[risk]}`}>{risk}</span> }
export function AlertBanner({alerts}:{alerts:ClinicalPatient['alerts']}) { if(!alerts.length) return null; return <div className='rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700'>{alerts.map(a=><div key={a.code} className='flex items-center gap-2'><AlertTriangle className='h-4 w-4'/>{a.label}</div>)}</div> }
export function PatientProfileCard({p}:{p:ClinicalPatient}){return <div className='grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-2 text-sm'><div><p className='font-semibold text-slate-900'>{p.name}</p><p>RM {p.medicalRecordNumber} • {p.age} • {p.gender}</p><p>{p.city} • Dokter: {p.doctor}</p><p>Diagnosis aktif: {p.activeDiagnosis}</p><p>Keluhan utama: {p.chiefComplaint}</p><p>Alergi: {p.allergies.join(', ')||'-'}</p><p>Obat aktif: {p.meds.join(', ')||'-'}</p></div><div><p>Riwayat sistemik: {p.systemicHistory.join(', ')||'-'}</p><p>Riwayat mata: {p.ocularHistory}</p><p>Operasi mata: {p.ocularSurgery}</p><p>Kontak darurat: {p.emergencyContact}</p><p>Risk reason: {p.riskReasons.join('; ')}</p></div></div>}
export function ClinicalTimeline({p}:{p:ClinicalPatient}){return <div className='space-y-2'>{p.timeline.map(t=><div key={t.date+t.complaint} className='rounded-lg border bg-white p-3 text-sm'><p className='font-semibold'>{t.date} • {t.status}</p><p>{t.complaint} | {t.diagnosis}</p><p>Tindakan: {t.procedure} • Resep: {t.prescription} • FU: {t.followUp}</p></div>)}</div>}
export function TaskBoard({patients}:{patients:ClinicalPatient[]}){const critical=patients.filter(p=>p.risk==='Critical').length;const pendingSoap=patients.filter(p=>!p.soap.approvedByDoctor).length;const overdue=patients.filter(p=>new Date(p.followUpDate)<new Date()).length;return <div className='grid gap-3 md:grid-cols-3'>{[['Pending SOAP review',pendingSoap],['Critical patient',critical],['Follow-up overdue',overdue]].map(([k,v])=><div key={String(k)} className='rounded-xl border bg-white p-3'><p className='text-xs text-slate-500'>{k}</p><p className='text-2xl font-bold'>{v}</p></div>)}</div>}
export function FollowUpScheduler({p,onChange}:{p:ClinicalPatient;onChange:(d:string,r:string)=>void}){const overdue = new Date(p.followUpDate)<new Date(); return <div className='rounded-xl border bg-white p-3 text-sm space-y-2'><p className='font-semibold'>Jadwal kontrol {overdue && <span className='ml-2 rounded bg-red-100 px-2 text-red-700'>Overdue</span>}</p><input type='date' value={p.followUpDate} onChange={e=>onChange(e.target.value,p.followUpReason)} className='rounded border px-2 py-1'/><input value={p.followUpReason} onChange={e=>onChange(p.followUpDate,e.target.value)} className='w-full rounded border px-2 py-1' placeholder='Next visit reason'/></div>}
export function PrescriptionPanel(){return <div className='rounded-xl border bg-white p-3 text-sm'>Prescription module active. Tambah obat dan warning steroid vs high IOP tersedia pada form utama.</div>}
export function ImagingReview(){return <div className='rounded-xl border bg-white p-3 text-sm'>Imaging review tersedia dengan tombol Review Image pada tab Imaging.</div>}
export function EyeExamForm(){return <div className='rounded-xl border bg-white p-3 text-sm'>Eye exam form OD/OS tersedia pada tab Eye Exam.</div>}
export function SoapEditor(){return <div className='rounded-xl border bg-white p-3 text-sm'>SOAP editor dengan template AI tersedia pada tab SOAP.</div>}
export function PatientTableFooter({page,total}:{page:number;total:number}){return <div className='flex items-center justify-between p-2 text-xs text-slate-500'>Page {page} • {total} patients<div className='flex gap-2'><Clock3 className='h-4 w-4'/><CheckCircle2 className='h-4 w-4'/></div></div>}
